### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by ludovicc** [madgik/exareme#2]
I tried to skip the tests, but the project still doesn't compile

[INFO] exareme-master ..................................... FAILURE [  1.923 s]
[INFO] exareme-distribution ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.692 s
[INFO] Finished at: 2015-10-15T16:32:46+02:00
[INFO] Final Memory: 32M/420M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project exareme-master: Could not resolve dependencies for project madgik:exareme-master:jar:0.1-SNAPSHOT: Could not find artifact madgik:exareme-worker:jar:tests:0.1-SNAPSHOT -> [Help 1]
[ERROR]

**Comment by alexpap** [comment]
check #1
