### ISSUE TITLE
Bug : Errors Management

### ISSUE THREAD

**Issue by mirco-nasuti** [madgik/exareme#50]
HTTP POST on  /mining/query/WP_LINEAR_REGRESSION using an invalid body e.g. an empty array '[]' returns http code 200 and a stacktrace (see below) in the response body. This behaviour is wrong.

java.rmi.ServerException: ; nested exception is: 
    java.rmi.ServerException: Cannot execute madis; nested exception is: 
    java.rmi.ServerException: Cannot run query; nested exception is: 
    java.rmi.ServerException: Cannot execute db (code: 1): Madis SQLError: 
Operator EXECNSELECT: Error in query no. 6 - list index out of range

**You should return an http error code (instead of 200) !**

**Comment by ThanKarab** [comment]
It is fixed.
